---
title: "Doing Genders: Partner’s Gender and Labor Market Behavior"
date: 2024-05-222
author:
  - name: Eva Jaspers
  - name: Deni Mazrekaj
  - name: Weverthon Machado
doi: "10.1177/00031224241252079"
reference: |
  Jaspers, Eva,  Deni Mazrekaj, and Weverthon Machado. 2024. ‘Doing Genders: Partner’s Gender and Labor Market Behavior’. <i>American Sociological Review</i> 89(3):518-541. <a href="https://doi.org/10.1177/00031224241252079">https://doi.org/10.1177/00031224241252079</a>
links: 
  - text: PDF
    icon: fa-solid fa-file-lines
    icon2: "{{< fa file-lines >}}"
    url: "https://journals.sagepub.com/doi/pdf/10.1177/00031224241252079"
  - text: Replication package
    icon: fa-solid fa-code
    icon2: "{{< fa code >}}"
    url: "https://osf.io/qpa8d/"
---

**Abstract** 

Partnered men and women show consistently gendered patterns of labor market behavior. We test whether not only a person’s own gender, but also their partner’s gender shapes hours worked. We use Dutch administrative population data on almost 5,000 persons who had both male and female partners, whose hours worked we observe monthly over 15 years. We argue that this provides a unique setting to assess the relevance of partner’s gender for labor market behavior. Using two-way fixed effects and fixed-effects individual slopes models, we find that both men and women tend to work more hours when partnered with a female partner compared to a male partner. These results align with our hypothesis that a partner’s gender influences labor market behavior. For women, we conclude that this finding may be (partly) explained by marital and motherhood status. Additionally, we discovered that women decrease their hours worked to a lesser extent when caring for a child if they have a female partner. Finally, we found that for men, the positive association between own and partner’s hours worked is weaker when one has a female partner, indicating a higher degree of specialization within these couples.

